global:                                                                         
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:                                                              
      monitor: 'exporter-metrics'                                                
                                                                                
scrape_configs:
- job_name: 'ContainerMetrics'
  dns_sd_configs:
  - names:
    - cadvisor
    refresh_interval: 15s
    type: A
    port: 8080

- job_name: 'Prometheus'
  static_configs:
    - targets:
      -  '127.0.0.1:9090'

- job_name: 'rancher'
  file_sd_configs:
    - files: [ '/prom-rancher-sd-data/rancher.json' ]
      refresh_interval: 30s
  relabel_configs:
  - source_labels: ['metrics_path']
    regex:         '(.*)'
    target_label:  '__metrics_path__'
    replacement:   '$1'

- job_name: 'NodeMetrics'
  file_sd_configs:
    - files: [ '/prom-rancher-sd-data/node_exporter.json' ]
      refresh_interval: 30s
