global:                                                                         
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:                                                              
      monitor: 'exporter-metrics'                                                
                                                                                
scrape_configs:
- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 30s
    type: A
    port: 9100

- job_name: 'ContainerMetrics'
  dns_sd_configs:
  - names:
    - ranch-eye
    refresh_interval: 30s
    type: A
    port: 9104

- job_name: 'Prometheus'
  static_configs:
    - targets:
      -  '127.0.0.1:9090'

- job_name: 'rancher'
  file_sd_configs:
    - files: [ '/prom-rancher-sd-data/*.json' ]
      refresh_interval: 30s
